### ISSUE TITLE
Can't launch grommet-site 

### ISSUE THREAD

**Issue by lasharela** [grommet/grommet-site#84]
I've just cloned grommet-site git. npm install and npm start (nothing special)

in a console of browser (Chrome 72) I see:

Uncaught Error: Module build failed (from ./node_modules/monaco-editor-webpack-plugin/loaders/include.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.pitch (:8567/Users/lasharela/Dev/hulbu/grommet-site/node_modules/monaco-editor-webpack-plugin/loaders/include.js:4)
    at eval (editor.api.js:1)
    at Object../node_modules/monaco-editor/esm/vs/editor/editor.api.js (main-8a0a0e27aa859223804a.js:12153)
    at __webpack_require__ (main-8a0a0e27aa859223804a.js:724)
    at fn (main-8a0a0e27aa859223804a.js:101)
    at eval (editor.js:11)
    at Object../node_modules/react-monaco-editor/lib/editor.js (main-8a0a0e27aa859223804a.js:13078)
    at __webpack_require__ (main-8a0a0e27aa859223804a.js:724)
    at fn (main-8a0a0e27aa859223804a.js:101)
    at eval (index.js:8)
    at Object../node_modules/react-monaco-editor/lib/index.js (main-8a0a0e27aa859223804a.js:13090)

I'm working on MacOS Mojave 10.14
npm 6.4.1
node 8.12.0

**Comment by stvmachine** [comment]
+1

**Comment by ShimiSun** [comment]
I used to see this error before but after cleaning up the project I don't see it anymore.
Can you please try to clean up all cached files and even a new clone to see if it reproduces, and let me know how it goes? 
`rm -rf node_modules`
`rm -rf package-lock.json`
`rm -rf yarn.lock`
`yarn cache clean`

**Comment by rjain15** [comment]
same here.....
ERROR in ./node_modules/monaco-editor/esm/vs/editor/editor.api.js
Module build failed (from ./node_modules/monaco-editor-webpack-plugin/loaders/include.js):
TypeError: loaderUtils.getOptions is not a function
    at Object.pitch (/Users/rjain/code/react-samples/grommet-site/node_modules/monaco-editor-webpack-plugin/loaders/include.js:4:68)
 @ ./node_modules/react-monaco-editor/lib/editor.js 11:14-63
 @ ./node_modules/react-monaco-editor/lib/index.js
 @ ./src/screens/Play.js
 @ ./src/components/Content.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8567 ./src/index.js

**Comment by rjain15** [comment]
works by install it latest loader-utils, seems there is some reference to older version of loader-utils
`npm install loader-utils@latest`

**Comment by ShimiSun** [comment]
```
rm -rf node_modules
rm -rf yarn.lock
rm -rf package-lock.json
yarn cache clean
npm start
```
clean all cache, run these commands and it should do the trick. works for me.

**Comment by ShimiSun** [comment]
Closing, feel free to reopen if still relevant after applying @rjain15 recommendation.
Thank you @rjain15 for helping the community!
